# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggergatedUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('usertype', models.CharField(max_length=256)),
                ('lowTemp', models.FloatField(blank=True, null=True)),
                ('referenceTemp', models.FloatField(blank=True, null=True)),
                ('referenceLife', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('organization_id', models.IntegerField()),
                ('raspberry_id', models.CharField(max_length=256)),
                ('event_type', models.CharField(max_length=256)),
                ('event_order', models.IntegerField()),
                ('is_current', models.BooleanField()),
                ('elapsed_seconds', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('client', models.CharField(blank=True, max_length=256, null=True)),
                ('read_point', models.CharField(blank=True, max_length=256, null=True)),
                ('biz_location', models.CharField(blank=True, max_length=256, null=True)),
                ('biz_step', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventsDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_json', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('usertype', models.CharField(max_length=256)),
                ('partnerName', models.CharField(blank=True, max_length=256, null=True)),
                ('segmentTypeDeparture', models.CharField(blank=True, max_length=256, null=True)),
                ('functionalName', models.CharField(blank=True, max_length=256, null=True)),
                ('partnerTypeStart', models.CharField(blank=True, max_length=256, null=True)),
                ('bizLocationTypeStart', models.CharField(blank=True, max_length=256, null=True)),
                ('packagingTypeCode', models.CharField(blank=True, max_length=256, null=True)),
                ('tradeItemCountryOfOrigin', models.CharField(max_length=256)),
                ('lowTemp', models.IntegerField()),
                ('referenceTemp', models.IntegerField()),
                ('referenceLife', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdata',
            unique_together=set([('owner_name', 'company', 'usertype')]),
        ),
        migrations.AddField(
            model_name='event',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactor.UserData'),
        ),
        migrations.AlterUniqueTogether(
            name='aggergateduserdata',
            unique_together=set([('company', 'usertype')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('time', 'organization_id', 'raspberry_id', 'event_type', 'event_order')]),
        ),
    ]
