# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('FTStopEvent', 'FTStopEvent'), ('FTInspectEvent', 'FTInspectEvent'), ('FTCommitEvent', 'FTCommitEvent'), ('FTHandoverEvent', 'FTHandoverEvent'), ('FTStartEvent', 'FTStartEvent'), ('FTClearEvent', 'FTClearEvent'), ('FTEnableEvent', 'FTEnableEvent'), ('FTResetEvent', 'FTResetEvent'), ('FTGroupEvent', 'FTGroupEvent'), ('FTUngroupEven', 'FTUngroupEven'), ('FTReadEvent', 'FTReadEvent'), ('FTCheckpointEvent', 'FTCheckpointEvent'), ('FTWriteEvent', 'FTWriteEvent')], max_length=256),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='usertype',
            field=models.CharField(choices=[('Shipment', 'Shipment'), ('Storage', 'Storage'), ('Manufacturer', 'Manufacturer'), ('Retailer', 'Retailer'), ('Grower', 'Grower')], max_length=256),
        ),
        migrations.AlterIndexTogether(
            name='userdata',
            index_together=set([('company', 'usertype'), ('owner_name', 'company', 'usertype')]),
        ),
    ]
