# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AggergatedUserData',
            new_name='AggregatedUserData',
        ),
    ]
