version: '2'
services:

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - "5672"

  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    ports:
      - "5432"

  web:
    links:
      - postgres
    restart: always
    build: ./hotorcold/
    image: hotorcold:1.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hotorcold/:/code/
    ports:
      - "8000:8000"

  celeryworker:
    image: hotorcold:1.1
    depends_on:
      - rabbit
    command: celery -A hotorcold worker -l INFO
  
volumes:
  db_data:
